---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-service
  namespace: vikunja
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.18
  selector:
    app.kubernetes.io/name: vikunja
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3456
