victoria-metrics-operator:
  admissionWebhooks:
    certManager:
      enabled: false
grafana:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.19"
vmsingle:
  enabled: false
vmcluster:
  enabled: true
  spec:
    retentionPeriod: "12"
    vmstorage:
      replicaCount: 2
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            resources:
              requests:
                storage: 20Gi
    vminsert:
      replicaCount: 2
    vmselect:
      replicaCount: 2
      serviceSpec:
        spec:
          type: LoadBalancer
          loadBalancerIP: "192.168.1.20"
