---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/aditaranto1028/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 29.9.0
      helm:
        valueFiles:
          - $values/kubernetes/prometheus/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
