---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 41.2.0
      helm:
        valueFiles:
          - $values/kubernetes/traefik/values.yaml
    - repoURL: https://github.com/aditaranto1028/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/aditaranto1028/homelab.git
      targetRevision: HEAD
      path: kubernetes/traefik/ingressRoutes
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
