---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: ntfy
      repoURL: https://repo.helmforge.dev
      targetRevision: 1.2.1
      helm:
        valueFiles:
          - $values/kubernetes/ntfy/values.yaml
    - repoURL: https://github.com/aditaranto1028/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy
