# Encrypt your secrets with the following command:
# kubeseal --format yaml < template-SealedSecret.yaml > [secret]-sealed.yaml; rm template-SealedSecret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: <SECRET_NAME>
  namespace: <NAMESPACE>
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/managed-by: sealed-secrets
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  <KEY_1>: <VALUE_1>
  <KEY_2>: <VALUE_2>
