---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCX3ExkZuKpJR5UNofFd88+vkGpPymL1lmJ4lHF9u8D9DiEe9DWwOu0N3zdiElIkVlnqFY8te6OJqI6R0bH8w+zkTmSIbIBLUbV37X5R4f5LaTPNr8CaBdcECurpDn5SuJMx8xvxj6QF22gxBmPQ+4I50Q/CBWGQdsc7bzZWiScnxlafr6hqDcOHODCLBkKCC5wuASTmTkxOZQZRavvUw63wzXQi2pA3YcJu5EQbAfWzVjC3j3xl7E3UT3PzGgIbOEHLmMsvV1v3L44fGgU+ZsyzuTh5NLAAxrmUuE8DbJz6zE+FERh2JGC7IlWaNzyQDfQCPcFVMCZhrA+bnxqhUw6/2J04Zz6zqfd24Ibw+mY8c8W1AoXVaO2qzF7lCGUuNt+pbtS7A2HQFCx/b5cnwnYk5KHpJm+VY0oQ2Iicyp2a9046I4KxHhwmmMBq6exLvBA+EW8raFJeErMgdloiJ8C304AyVtbxXaythS2TGmKUk04WGn4N6IG2O6w/BXWXmiqVdbI5ddlwST7LZIXOGOA1scbRnhijcLMrEskI/le6fdnOAQE9GPZiuYZEXS28Fuc+w0XD60YjTpIOIJ7zAh2lMmkfahLD5Iq3eggS6EgmrjWsRSQjnFZ5ox8a4JB8nn1Ltr1FT5Ms5to+0NXKC4XFda9sEVbPtgw4aR1FQ3ad6aPZgBFLp2xOp9VcIKgZKe84HhszT8/ucqXOzRGGuW8aAxPuhJHjGWsQrYeERkRVXjZkfWLdNZSKY58W10oexTPROOemg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/managed-by: sealed-secrets
        app.kubernetes.io/name: sealed-secrets
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
