---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgBx0SyiTBcOKRn/4c2PNBjcphcO70HsZUEVWWbalkvHkQAMu4YJQQBqUdZhJRKy3MH0X8xCL6AidBd7t4iXlQQ7BvL3d5v8Mhhxz5gKiyBJyvAZq7kuXnlWYkNhVgCrYp8n3n+wl7sZdzXXQEkLvHWmvKYMi/OdnL/bVmwMbyzwDnyrZwJ0WMngEpPcw1Qt8gSPfXbEH1pXhumGCkEuC7RlPUhES3YPPosB9PNzwER/MOqo/k3jassAd7rWR5bwnBAupRzRcPmlzsXev4X+C9PcpoTtlAfNezfFEE/Yw5/Rh99IWSDfb3+LTTwC5aX3gII7nrC2PHFR9sH3F2KLNDUBR/sUP3xW6EIxOM80ZIyV9GoY7pRta9tlPl/GZWqZyEZTUqlTHBYDtxKxTH6/JW04aIbcEpm4MI61Bh1fbLilpD/llgjosDDrPlYqDEXMmZ0CjfYgePGsmXmb2qN4QbEmcYN/ACET3BzQTUFQgAsriO6ZGWi7SOTR+WbubCCHqEW4lxIEGoTyieK3qmsZlA9Hlx51+ZXJbwOfBoTniTIVUVmjHwjcFeGaYRIyNMBngu6a9Agf4ySNhssqN2LD52wxDqn0mU0kcdO0rbrI+DZIt8JB9bUr6Wsehd5QXV6RuukHm8X1hnNe0sCxrmON+tbkUUVkObs+BN8Q4cvKzS2Xfj6JZB8fxY9AmwgqaQlPQQ6VM5UFshXfO5M=
    username: AgCNU9inSQd2BOQSnG+LtHbWmaJHMNXDTyodP/LGEfsqT5r92FDBTe1cbRY7uxlTmQfZIKQvlqY2i9r0beFYsSB6dV8VFNakgYlwkuPmHQe3U/cSh4RVWzxALJGoTcTy7wKLe78iWDg21qtrx3kWnsrtjeorEN6dniTG/lUwMdkqBOUiCg6kEQsN8LU0gpTBNTAoHA7WdkD2Jlel+JUwEDhebaVjzS/BfQsu0V8yvmVQFkZyJd+wjSCv1JkmiITefHLNuAFLlL/KQic/jutJS8vC/LUJPm2LSwaRtApWl8SwUBq+iWqkYVfbVbU1VCfb5EAg8Jc7+nlEMrb78/lnriWgNLMKhmEbrdWo8/wvS6jOFuaLfhxRTMDsxsOrLbTH8KtUtz57LtALepnkvSkGfQWZELrTp8PzXQPo2YlbCxqjyTTd4vQF4WzF3wPyKU9dlAPhc/yGQ4zfB5GD5ePypYh892ZNwgHA7rNf0+tD3kGXW1YNDWawW66KM1f5hoSmeBlHfFmszRe4MEZTtnBY4a6tGNt4h5+AwEALLkxKfBO43hcuEKKrsyazPMO/cb7NRXD+KoqBKg+8l2uOa1rLU7s4yMRS5A6Foe+yROesmmBfIvuShi/zxAURRY8PoVlHf7xjhoUvMp6A0q4G+cdvKBK4saVn3mZMP0bxOorf44xiVNsYGSEjKjOpyRtwX8lwdvOloT0RvA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/managed-by: sealed-secrets
        app.kubernetes.io/name: sealed-secrets
      name: demo-secret
      namespace: default
    type: Opaque
