---
general:
  domain: http://192.168.1.11:30080
  admins:
    - aditaranto1028@gmail.com
  ingress:
    enabled: false
  signupsAllowed: false
  invitationsAllowed: true
  websocket:
    enabled: true
global:
  environment: production
  logLevel: info
service:
  type: NodePort
  nodePort: 30080
persistence:
  accessMode: ReadWriteOnce
  size: 4Gi
  enabled: true
  storageClassName: longhorn
